server:
  port: 8100

spring:
  application:
    name: file
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
      resolve-lazily: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

swagger:
  apiBasePackage: "com.example.file.controller"
  title: "文件服务"
  description: "文件服务"
  version: "1.0"
  contactName: "wxy"
  contactUrl: "www.wxyjj.top"
  contactEmail: "1083762642@qq.com"