spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.71.93:3306/pdddrugstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    username: root
    password: HuangQing
    hikari:
      connection-test-query: 'select 1 from dual'
      connection-timeout: 100000
      validation-timeout: 100000
      idle-timeout: 600000
      max-lifetime: 1800000
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: ${spring.datasource.platform}
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: com.example.common.support.MySqlInnoDbDialect
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true