spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.194:3306/rtdl?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      connection-test-query: 'select 1 from dual'
      connection-timeout: 100000
      validation-timeout: 100000
      idle-timeout: 600000
      max-lifetime: 1800000
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: ${spring.datasource.platform}
    show-sql: true
    generate-ddl: false
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true