server:
  port: 8000

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: file
          uri: lb://file/
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ums
          uri: lb://ums/
          predicates:
            - Path=/ums/**
          filters:
            - StripPrefix=1
#配置RSA的公钥访问地址
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://127.0.0.1:8000/auth/rsa/publicKey'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

ignore:
  urls:
    - "/doc.html"
    - "/webjars/**"
    - "/swagger-resources/**"
    - "/favicon.ico"
    - "/*/v2/api-docs"
    - "/auth/oauth/token"
    - "/auth/rsa/publicKey"