spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  redis:
    database: 0
    host: 192.168.1.196
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    timeout: 3000ms
    password: 831001@Hq
  data:
    redis:
      repositories:
        enabled: false