server:
  port: 8300

spring:
  application:
    name: ums
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

swagger:
  apiBasePackage: "com.example.ums.controller"
  title: "用户服务"
  description: "用户服务"
  version: "1.0"
  contactName: "wxy"
  contactUrl: "www.wxyjj.top"
  contactEmail: "1083762642@qq.com"