spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.1.196:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    username: root
    password: 831001@Hq
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-test-query: select 1 from dual
  jpa:
    database: ${spring.datasource.platform}
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: com.example.ums.MySqlInnoDbDialect
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    database: 1
    host: 192.168.1.196
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    timeout: 3000ms
    password: 831001@Hq
  data:
    redis:
      repositories:
        enabled: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  mail:
    host: smtp.163.com
    username: a18723837421@163.com
    password: BBQXJUJVSWDCOOJK
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true