server:
  port: 8400

netty:
  port: 8410
  path: /netty

spring:
  application:
    name: netty
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

swagger:
  apiBasePackage: "com.example.netty.controller"
  title: "Netty服务"
  description: "Netty服务"
  version: "1.0"
  contactName: "wxy"
  contactUrl: "www.wxyjj.top"
  contactEmail: "1083762642@qq.com"