server:
  port: 8500

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: pdd
          uri: lb://pdd/
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
          predicates:
            - Path=/pdd/**
        - id: wxyf
          uri: lb://wxyf/
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
          predicates:
            - Path=/wxyf/**
        - id: hpyf
          uri: lb://hpyf/
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
          predicates:
            - Path=/hpyf/**
      discovery:
        locator:
          enabled: true
